const CONFIG={musicVolume:.7,images:{first:'Data/Img/a1.jpeg',second:'Data/Img/a2.jpeg',third:'Data/Img/a3.jpeg',fourth:'Data/Img/a4.jpeg',fifth:'Data/Img/a5.jpeg',sixth:'Data/Img/a6.jpeg',main:'Data/Img/a7.jpeg',eighth:'Data/Img/a8.jpeg',ninth:'Data/Img/a9.jpeg',tenth:'Data/Img/a10.jpeg',eleventh:'Data/Img/a11.jpeg',twelfth:'Data/Img/a12.jpeg',thirteenth:'Data/Img/a13.jpeg',fourteenth:'Data/Img/a14.jpeg',fifteenth:'Data/Img/a15.jpeg',sixteenth:'Data/Img/a16.jpeg'},audio:'Data/song/Song1.mpeg'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const music=$('#backgroundMusic'),toast=$('#toast');
function typeText(text,el,speed=42){return new Promise(resolve=>{el.textContent='';let i=0;const timer=setInterval(()=>{el.textContent+=text[i++];if(i===text.length){clearInterval(timer);resolve()}},speed)})}
async function openingSequence(){const line=$('#typedText');for(const text of ['I could have simply asked you one question…','But you deserve something more than a question.','So I made you a little journey.','A story written by one person…','MURAAD.','for one person.','You.']){await typeText(text,line);await wait(1150);line.style.opacity=0;await wait(550);line.style.opacity=1}line.textContent='';$('#enterWrap').classList.add('visible')}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function startStory(){music.volume=CONFIG.musicVolume;music.play().catch(()=>showToast('Tap ♫ to start the music.'));$('#opening').style.opacity=0;setTimeout(()=>{$('#opening').hidden=true;$('#story').hidden=false;$('#musicControl').hidden=false;$('.progress').hidden=false;setupPhotoPresentation();setupScrollAnimations();window.scrollTo(0,0);showToast('Take your time. MURAAD made this slowly.')},700)}
function setupPhotoPresentation(){$$('.hero-photo,.photo-frame,.memory-card,.main-photo').forEach(frame=>{const image=frame.querySelector('img');if(!image)return;const setBackground=()=>frame.style.setProperty('--photo',`url("${image.currentSrc||image.src}")`);if(image.complete&&image.naturalWidth)setBackground();else image.addEventListener('load',setBackground,{once:true});image.addEventListener('error',()=>{console.error(`Image failed to load: ${image.getAttribute('src')}`);frame.classList.add('image-missing');showToast('This memory is taking a little longer to arrive…')},{once:true})})}
function setupScrollAnimations(){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.17});$$('.fade-up,.fade-left,.fade-right,.zoom-in,.blur-in').forEach(el=>observer.observe(el));setupBuildup();setupMainReveal()}
function setupPuzzleOne(){const correctAnswer=2,buttons=$$('#puzzleOne .answers button'),feedback=$('#puzzleOne .puzzle-feedback'),next=$('#puzzleOne .continue-button');buttons.forEach((button,i)=>button.addEventListener('click',()=>{if(i===correctAnswer){button.classList.add('correct');feedback.textContent='You remembered. ♥';buttons.forEach(b=>b.disabled=true);next.disabled=false}else{button.classList.add('wrong');feedback.textContent='Nope. Nice try though.';setTimeout(()=>button.classList.remove('wrong'),700)}}));next.onclick=()=>$('#puzzleOne').nextElementSibling.scrollIntoView({behavior:'smooth'})}
function setupPuzzleTwo(){const field=$('.letter-field'),target='MURAAD',letters=['M','✦','U','?','R','A','○','A','D','✧','L','S'],collected=$('.collected');let index=0;letters.sort(()=>Math.random()-.5).forEach(letter=>{const b=document.createElement('button');b.textContent=letter;b.setAttribute('aria-label',`Letter ${letter}`);b.onclick=()=>{if(letter===target[index]){b.classList.add('found');index++;collected.textContent=target.slice(0,index).split('').join(' ');if(index===target.length){$('.message-unlocked').hidden=false}}else showToast('Not that one — look a little closer.')};field.append(b)})}
function setupBuildup(){const section=$('.buildup'),lines=$$('.buildup-lines p'),heading=$('.buildup h2');new IntersectionObserver(entries=>{if(entries[0].isIntersecting){lines.forEach((line,i)=>setTimeout(()=>line.classList.add('visible'),i*1150));setTimeout(()=>heading.classList.add('visible'),lines.length*1150)}},{threshold:.55}).observe(section)}
function setupMainReveal(){const section=$('.main-reveal'),lines=$$('.reveal-copy p'),photo=$('.main-photo');new IntersectionObserver(entries=>{if(entries[0].isIntersecting){lines.forEach((line,i)=>setTimeout(()=>line.classList.add('visible'),i*1050));setTimeout(()=>photo.classList.add('revealed'),4600)}},{threshold:.35}).observe(section)}
function setupFinalQuestion(){$('#askButton').onclick=()=>{$('#askButton').hidden=true;$('#questionGame').hidden=false;const choices=$$('#questionGame .answers button'),feedback=$('#questionGame .puzzle-feedback');choices.forEach((b,i)=>b.onclick=()=>{if(i===1){feedback.innerHTML='It’s wherever you are.<br><br>Do you know my favourite notification?<br>It’s your name appearing on my screen.<br><br><em>But… that wasn’t the question I actually wanted to ask.</em>';choices.forEach(x=>x.disabled=true);setTimeout(()=>{$('#proposal').hidden=false;$('#proposal').scrollIntoView({behavior:'smooth'})},4200)}else{feedback.textContent='Wrong.'}})}}
function showResponse(type){$('#proposal').hidden=true;$('#response').hidden=false;$(`#${type}Response`).hidden=false;if(type==='yes')celebrate();$('#response').scrollIntoView({behavior:'smooth'})}
function celebrate(){for(let i=0;i<35;i++){const p=document.createElement('i');p.textContent='♥';p.style.cssText=`position:fixed;z-index:25;left:${Math.random()*100}vw;top:${70+Math.random()*30}vh;color:${Math.random()>.5?'#d95b6d':'#d7b376'};font-style:normal`;$('#particles').append(p);p.animate([{transform:'translateY(0) scale(.7)',opacity:0},{opacity:.95,offset:.2},{transform:`translate(${(Math.random()-.5)*90}px,-${220+Math.random()*260}px) scale(1.2)`,opacity:0}],{duration:2800+Math.random()*900,easing:'ease-out'});setTimeout(()=>p.remove(),3800)}}
function setupEasterEggs(){$('#easterEgg').onclick=()=>showToast('You found me hiding here. ♥');document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m')showToast('Tumhare bina bhi din guzarta hai, par tumhare saath din yaad reh jaata hai.')})}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function setupProgress(){addEventListener('scroll',()=>{$('.progress b').style.height=`${Math.min(100,scrollY/(document.body.scrollHeight-innerHeight)*100)}%`},{passive:true})}
$('#enterStory').onclick=startStory;$('#musicControl').onclick=()=>{if(music.paused){music.play();$('#musicControl span').textContent='Playing'}else{music.pause();$('#musicControl span').textContent='Music'}};music.addEventListener('play',()=>$('#musicControl span').textContent='Playing');music.addEventListener('error',()=>showToast("Tap the music icon if the song didn’t start."));$('#yesButton').onclick=()=>showResponse('yes');$('#thinkButton').onclick=()=>showResponse('think');$$('.letter-button').forEach(b=>b.onclick=()=>{$('#letter').hidden=false;$('#letter').scrollIntoView({behavior:'smooth'})});openingSequence();setupPuzzleOne();setupPuzzleTwo();setupFinalQuestion();setupEasterEggs();setupProgress();
